/*
 * This file is generated by jOOQ.
 */
package com.bank.jooq.tables.records;


import com.bank.jooq.tables.Transferdetails;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransferdetailsRecord extends UpdatableRecordImpl<TransferdetailsRecord> implements Record6<UUID, UUID, UUID, BigDecimal, String, OffsetDateTime> {

    private static final long serialVersionUID = 1893781307;

    /**
     * Setter for <code>PUBLIC.TRANSFERDETAILS.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFERDETAILS.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFERDETAILS.RECEIVER_ID</code>.
     */
    public void setReceiverId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFERDETAILS.RECEIVER_ID</code>.
     */
    public UUID getReceiverId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFERDETAILS.SENDER_ID</code>.
     */
    public void setSenderId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFERDETAILS.SENDER_ID</code>.
     */
    public UUID getSenderId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFERDETAILS.AMOUNT</code>.
     */
    public void setAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFERDETAILS.AMOUNT</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFERDETAILS.STATUS</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFERDETAILS.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFERDETAILS.CREATED_ON</code>.
     */
    public void setCreatedOn(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFERDETAILS.CREATED_ON</code>.
     */
    public OffsetDateTime getCreatedOn() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, UUID, BigDecimal, String, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, UUID, UUID, BigDecimal, String, OffsetDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Transferdetails.TRANSFERDETAILS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Transferdetails.TRANSFERDETAILS.RECEIVER_ID;
    }

    @Override
    public Field<UUID> field3() {
        return Transferdetails.TRANSFERDETAILS.SENDER_ID;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Transferdetails.TRANSFERDETAILS.AMOUNT;
    }

    @Override
    public Field<String> field5() {
        return Transferdetails.TRANSFERDETAILS.STATUS;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Transferdetails.TRANSFERDETAILS.CREATED_ON;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getReceiverId();
    }

    @Override
    public UUID component3() {
        return getSenderId();
    }

    @Override
    public BigDecimal component4() {
        return getAmount();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public OffsetDateTime component6() {
        return getCreatedOn();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getReceiverId();
    }

    @Override
    public UUID value3() {
        return getSenderId();
    }

    @Override
    public BigDecimal value4() {
        return getAmount();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public OffsetDateTime value6() {
        return getCreatedOn();
    }

    @Override
    public TransferdetailsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public TransferdetailsRecord value2(UUID value) {
        setReceiverId(value);
        return this;
    }

    @Override
    public TransferdetailsRecord value3(UUID value) {
        setSenderId(value);
        return this;
    }

    @Override
    public TransferdetailsRecord value4(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public TransferdetailsRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public TransferdetailsRecord value6(OffsetDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public TransferdetailsRecord values(UUID value1, UUID value2, UUID value3, BigDecimal value4, String value5, OffsetDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransferdetailsRecord
     */
    public TransferdetailsRecord() {
        super(Transferdetails.TRANSFERDETAILS);
    }

    /**
     * Create a detached, initialised TransferdetailsRecord
     */
    public TransferdetailsRecord(UUID id, UUID receiverId, UUID senderId, BigDecimal amount, String status, OffsetDateTime createdOn) {
        super(Transferdetails.TRANSFERDETAILS);

        set(0, id);
        set(1, receiverId);
        set(2, senderId);
        set(3, amount);
        set(4, status);
        set(5, createdOn);
    }
}
