/*
 * This file is generated by jOOQ.
 */
package com.bank.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = -1692304552;

    private UUID       id;
    private String     name;
    private BigDecimal balance;

    public Account() {}

    public Account(Account value) {
        this.id = value.id;
        this.name = value.name;
        this.balance = value.balance;
    }

    public Account(
        UUID       id,
        String     name,
        BigDecimal balance
    ) {
        this.id = id;
        this.name = name;
        this.balance = balance;
    }

    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getBalance() {
        return this.balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Account other = (Account) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (balance == null) {
            if (other.balance != null)
                return false;
        }
        else if (!balance.equals(other.balance))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.balance == null) ? 0 : this.balance.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(balance);

        sb.append(")");
        return sb.toString();
    }
}
