/*
 * This file is generated by jOOQ.
 */
package com.bank.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transferdetails implements Serializable {

    private static final long serialVersionUID = 1554285517;

    private UUID           id;
    private UUID           receiverId;
    private UUID           senderId;
    private BigDecimal     amount;
    private String         status;
    private OffsetDateTime createdOn;

    public Transferdetails() {}

    public Transferdetails(Transferdetails value) {
        this.id = value.id;
        this.receiverId = value.receiverId;
        this.senderId = value.senderId;
        this.amount = value.amount;
        this.status = value.status;
        this.createdOn = value.createdOn;
    }

    public Transferdetails(
        UUID           id,
        UUID           receiverId,
        UUID           senderId,
        BigDecimal     amount,
        String         status,
        OffsetDateTime createdOn
    ) {
        this.id = id;
        this.receiverId = receiverId;
        this.senderId = senderId;
        this.amount = amount;
        this.status = status;
        this.createdOn = createdOn;
    }

    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getReceiverId() {
        return this.receiverId;
    }

    public void setReceiverId(UUID receiverId) {
        this.receiverId = receiverId;
    }

    public UUID getSenderId() {
        return this.senderId;
    }

    public void setSenderId(UUID senderId) {
        this.senderId = senderId;
    }

    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public OffsetDateTime getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(OffsetDateTime createdOn) {
        this.createdOn = createdOn;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Transferdetails other = (Transferdetails) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (receiverId == null) {
            if (other.receiverId != null)
                return false;
        }
        else if (!receiverId.equals(other.receiverId))
            return false;
        if (senderId == null) {
            if (other.senderId != null)
                return false;
        }
        else if (!senderId.equals(other.senderId))
            return false;
        if (amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!amount.equals(other.amount))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.receiverId == null) ? 0 : this.receiverId.hashCode());
        result = prime * result + ((this.senderId == null) ? 0 : this.senderId.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Transferdetails (");

        sb.append(id);
        sb.append(", ").append(receiverId);
        sb.append(", ").append(senderId);
        sb.append(", ").append(amount);
        sb.append(", ").append(status);
        sb.append(", ").append(createdOn);

        sb.append(")");
        return sb.toString();
    }
}
