/*
 * This file is generated by jOOQ.
 */
package com.bank.jooq;


import com.bank.jooq.tables.Account;
import com.bank.jooq.tables.FlywaySchemaHistory;
import com.bank.jooq.tables.Transferdetails;
import com.bank.jooq.tables.records.AccountRecord;
import com.bank.jooq.tables.records.FlywaySchemaHistoryRecord;
import com.bank.jooq.tables.records.TransferdetailsRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> CONSTRAINT_E = UniqueKeys0.CONSTRAINT_E;
    public static final UniqueKey<TransferdetailsRecord> CONSTRAINT_9 = UniqueKeys0.CONSTRAINT_9;
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TransferdetailsRecord, AccountRecord> TRANSFERDETAILS_RECEIVER_ID_FK = ForeignKeys0.TRANSFERDETAILS_RECEIVER_ID_FK;
    public static final ForeignKey<TransferdetailsRecord, AccountRecord> TRANSFERDETAILS_SENDER_ID_FK = ForeignKeys0.TRANSFERDETAILS_SENDER_ID_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountRecord> CONSTRAINT_E = Internal.createUniqueKey(Account.ACCOUNT, "CONSTRAINT_E", Account.ACCOUNT.ID);
        public static final UniqueKey<TransferdetailsRecord> CONSTRAINT_9 = Internal.createUniqueKey(Transferdetails.TRANSFERDETAILS, "CONSTRAINT_9", Transferdetails.TRANSFERDETAILS.ID);
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<TransferdetailsRecord, AccountRecord> TRANSFERDETAILS_RECEIVER_ID_FK = Internal.createForeignKey(com.bank.jooq.Keys.CONSTRAINT_E, Transferdetails.TRANSFERDETAILS, "TRANSFERDETAILS_RECEIVER_ID_FK", Transferdetails.TRANSFERDETAILS.RECEIVER_ID);
        public static final ForeignKey<TransferdetailsRecord, AccountRecord> TRANSFERDETAILS_SENDER_ID_FK = Internal.createForeignKey(com.bank.jooq.Keys.CONSTRAINT_E, Transferdetails.TRANSFERDETAILS, "TRANSFERDETAILS_SENDER_ID_FK", Transferdetails.TRANSFERDETAILS.SENDER_ID);
    }
}
