/*
 * This file is generated by jOOQ.
 */
package com.bank.jooq;


import com.bank.jooq.tables.Account;
import com.bank.jooq.tables.FlywaySchemaHistory;
import com.bank.jooq.tables.Transferdetails;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ACCOUNT</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>PUBLIC.TRANSFERDETAILS</code>.
     */
    public static final Transferdetails TRANSFERDETAILS = Transferdetails.TRANSFERDETAILS;

    /**
     * The table <code>PUBLIC.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
