/*
 * This file is generated by jOOQ.
 */
package com.bank.jooq.tables.daos;


import com.bank.jooq.tables.Transferdetails;
import com.bank.jooq.tables.records.TransferdetailsRecord;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransferdetailsDao extends DAOImpl<TransferdetailsRecord, com.bank.jooq.tables.pojos.Transferdetails, UUID> {

    /**
     * Create a new TransferdetailsDao without any configuration
     */
    public TransferdetailsDao() {
        super(Transferdetails.TRANSFERDETAILS, com.bank.jooq.tables.pojos.Transferdetails.class);
    }

    /**
     * Create a new TransferdetailsDao with an attached configuration
     */
    public TransferdetailsDao(Configuration configuration) {
        super(Transferdetails.TRANSFERDETAILS, com.bank.jooq.tables.pojos.Transferdetails.class, configuration);
    }

    @Override
    public UUID getId(com.bank.jooq.tables.pojos.Transferdetails object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bank.jooq.tables.pojos.Transferdetails> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Transferdetails.TRANSFERDETAILS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.bank.jooq.tables.pojos.Transferdetails> fetchById(UUID... values) {
        return fetch(Transferdetails.TRANSFERDETAILS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.bank.jooq.tables.pojos.Transferdetails fetchOneById(UUID value) {
        return fetchOne(Transferdetails.TRANSFERDETAILS.ID, value);
    }

    /**
     * Fetch records that have <code>RECEIVER_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bank.jooq.tables.pojos.Transferdetails> fetchRangeOfReceiverId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Transferdetails.TRANSFERDETAILS.RECEIVER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>RECEIVER_ID IN (values)</code>
     */
    public List<com.bank.jooq.tables.pojos.Transferdetails> fetchByReceiverId(UUID... values) {
        return fetch(Transferdetails.TRANSFERDETAILS.RECEIVER_ID, values);
    }

    /**
     * Fetch records that have <code>SENDER_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bank.jooq.tables.pojos.Transferdetails> fetchRangeOfSenderId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Transferdetails.TRANSFERDETAILS.SENDER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>SENDER_ID IN (values)</code>
     */
    public List<com.bank.jooq.tables.pojos.Transferdetails> fetchBySenderId(UUID... values) {
        return fetch(Transferdetails.TRANSFERDETAILS.SENDER_ID, values);
    }

    /**
     * Fetch records that have <code>AMOUNT BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bank.jooq.tables.pojos.Transferdetails> fetchRangeOfAmount(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(Transferdetails.TRANSFERDETAILS.AMOUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>AMOUNT IN (values)</code>
     */
    public List<com.bank.jooq.tables.pojos.Transferdetails> fetchByAmount(BigDecimal... values) {
        return fetch(Transferdetails.TRANSFERDETAILS.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>STATUS BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bank.jooq.tables.pojos.Transferdetails> fetchRangeOfStatus(String lowerInclusive, String upperInclusive) {
        return fetchRange(Transferdetails.TRANSFERDETAILS.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>STATUS IN (values)</code>
     */
    public List<com.bank.jooq.tables.pojos.Transferdetails> fetchByStatus(String... values) {
        return fetch(Transferdetails.TRANSFERDETAILS.STATUS, values);
    }

    /**
     * Fetch records that have <code>CREATED_ON BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.bank.jooq.tables.pojos.Transferdetails> fetchRangeOfCreatedOn(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Transferdetails.TRANSFERDETAILS.CREATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATED_ON IN (values)</code>
     */
    public List<com.bank.jooq.tables.pojos.Transferdetails> fetchByCreatedOn(OffsetDateTime... values) {
        return fetch(Transferdetails.TRANSFERDETAILS.CREATED_ON, values);
    }
}
